name: Deploy to EC2

on: 
  push:
    branches:
      - main
      - v2-new-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: clean old dist
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /home/ubuntu/bukabuku/docker/app/wp-content/themes/mytheme/dist/*

      - name: Debug build output
          run: |
            echo "=== FRONTEND FOLDER ==="
            ls -la frontend

            echo "=== DIST FOLDER ==="
            ls -la frontend/dist || echo "dist not found"

      - name: Copy frontend build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".frontend/dist/*"
          target: "/home/ubuntu/bukabuku/docker/app/wp-content/themes/mytheme/"
          strip_components: 2
          overwrite: true
      
      - name: restart docker-compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/bukabuku/docker
            docker-compose restart