name: Deploy to EC2

on: 
  push:
    branches:
      - main
      - v2-new-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: clean old dist
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /home/ubuntu/bukabuku/docker/app/wp-content/themes/mytheme/dist
            sudo rm -rf /home/ubuntu/bukabuku/docker/app/wp-content/themes/mytheme/dist/*
      
      - name: Debug build output
        run: |
          echo "=== FRONTEND FOLDER ==="
          ls -la frontend

          echo "=== DIST FOLDER ==="
          ls -la frontend/dist || echo "dist not found"
      
      - name: Debug dist content
        run: |
          echo "=== DIST CONTENT ==="
          ls -la frontend/dist
      
      - name: Clean dist folder on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /home/ubuntu/bukabuku/docker/app/wp-content/themes/mytheme/dist/*

      - name: Copy frontend build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist"
          target: "/home/ubuntu/tmp/deploy/"
          overwrite: true

      - name: Move files to theme (sudo)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/bukabuku/docker/app/wp-content/themes/mytheme/dist/*
            sudo cp -r /home/ubuntu/tmp-deploy/frontend/dist/* /home/ubuntu/bukabuku/docker/app/wp-content/themes/mytheme/dist/
            sudo chown -R ubuntu:www-data /home/ubuntu/bukabuku/docker/app/wp-content/themes/mytheme/dist
            rm -rf /home/ubuntu/tmp-deploy

      - name: restart docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/bukabuku/docker
            docker compose up -d --remove-orphans